[package]
name = "mackerel_plugin"
version = "0.2.3"
authors = ["itchyny <itchyny@hatena.ne.jp>"]
description = "Mackerel plugin helper library"
repository = "https://github.com/itchyny/mackerel-plugin-rs"
readme = "README.md"
license = "MIT"
keywords = ["cli", "mackerel"]

[dependencies]
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.33"
time = "0.1"
rand = "0.5"
