[package]
name = "mackerel_plugin"
version = "0.2.4"
authors = ["itchyny <itchyny@hatena.ne.jp>"]
description = "Mackerel plugin helper library"
repository = "https://github.com/itchyny/mackerel-plugin-rs"
readme = "README.md"
license = "MIT"
keywords = ["cli", "mackerel"]

[dependencies]
serde = "1.0.114"
serde_derive = "1.0.114"
serde_json = "1.0.56"
rand = "0.7.3"
